version: '3.9'

services:
  # postgres:
  #   build:
  #     context: infra/rdb
  #     dockerfile: Dockerfile
  #   environment:
  #     POSTGRES_DB: fruits_trading_demo_db
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: fruits_trading_demo_pass
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"

  localstack:
    build:
      context: infra/ddb
      dockerfile: Dockerfile
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=your-access-key-id
      - AWS_SECRET_ACCESS_KEY=your-secret-access-key
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodb-admin:
    build: 
      context: infra/ddb/dynamodb-admin
      dockerfile: Dockerfile
    ports:
      - "8001:8001" 
    depends_on:
      - localstack

# volumes:
#   postgres-data: